[ZV-186] Контракт для LotService
ZveronHSE/contract pull request #6
Opened 2023-01-12 18:39 UTC by WolfAlm

2023-01-13 22:12 UTC, WolfAlm commented on lot/src/proto/manage/manage_lot.proto
> +message Address {
спасибо!

2023-01-13 22:12 UTC, WolfAlm commented on lot/src/proto/preview/preview_lot.proto
> +message PreviewLotResponse {
Да, я что-то тогда не додумалась до лучшего варианта, сейчас в голову пришло CardLot. Спасибо от души!

2023-01-13 22:12 UTC, WolfAlm commented on lot/src/proto/lot.proto
> +  int32 seller_id = 1;
да, это единственное место, где я подумала, что будет непонятно и указала явно, но потом посмотрела по методу и кажется понятно чего ждут, поменяла

еще тут почти не заметила что int32, а не int64))

2023-01-14 23:47 UTC, Schuyweiz requested changes

2023-01-14 23:47 UTC, Schuyweiz commented on lot/src/proto/card/card_lot.proto
> +message CardLotRequest {
может `GetCardLotRequest`? без действия название не очень информативно

2023-01-14 23:47 UTC, Schuyweiz commented on lot/src/proto/card/card_lot.proto
> +  string price = 8;
то есть нам нужно будет это распаршивать и надеяться, что мобильщики не подложат туда не цену?)

2023-01-14 23:47 UTC, Schuyweiz commented on lot/src/proto/card/card_lot.proto
> +  bool is_favorite = 9;
is_own и is_favorite звучит как список енамов, где есть IS_PERSONAL, IS_FAVOURITE, особенно если захотим еще состояний накинуть как там не знаю, горячее предложение и тп, что думаешь

2023-01-14 23:47 UTC, Schuyweiz commented on lot/src/proto/card/card_lot.proto
> +  Photo photo = 6;
надо бы подумать как дтошки обогащать фотками в апигее, а не вытаскивать их из бд кмк

2023-01-14 23:47 UTC, Schuyweiz commented on lot/src/proto/card/card_lot.proto
> +  WaysOfCommunicating ways_of_communicating = 1;
не нравится название, я бы предложил `CommunicationChannel` или просто `Channel`

2023-01-14 23:47 UTC, Schuyweiz commented on lot/src/proto/card/card_lot.proto
> +  LinksToContacts links_to_contacts = 2;
думаю просто `Links` в контексте контакта говорит достаточно

2023-01-14 23:47 UTC, Schuyweiz commented on lot/src/proto/card/card_lot.proto
> +  LinksToContacts links_to_contacts = 2;
может быть даже `ChannelLink`

2023-01-14 23:47 UTC, Schuyweiz commented on lot/src/proto/manage/manage_lot.proto
> +  CreateAddress address = 8;
просто `Address`?

2023-01-14 23:47 UTC, Schuyweiz commented on lot/src/proto/manage/manage_lot.proto
> +  SOLD_SOMEWHERE = 1;
я бы предложил `SOLD_EXTERNAL`, somewhere как-то неинформативно

2023-01-14 23:47 UTC, Schuyweiz commented on lot/src/proto/model_lot.proto
> +  // Если цены нет, то придет текст, например "Договорная", а если есть цена - то число. Этим и обусловен выбор string тут.
вообще чем больше думаю об этом, тем больше хз, как-то не интуитивно, что цена при 0 прревращается в договорную, кажется что это к мобильщика отрисовывать, а мы бы им предоставили какой нибудь словарь

2023-01-14 23:47 UTC, Schuyweiz commented on lot/src/proto/model_lot.proto
> +  string date_of_publication = 4;
а мы на бек не можем сразу получать например таймстамп? Очень не люблю даты
`publication_date`

2023-01-14 23:47 UTC, Schuyweiz commented on lot/src/proto/model_lot.proto
> +  METIS = 2;
сначала подумал это блять для продавца

2023-01-14 23:47 UTC, Schuyweiz commented on lot/src/proto/model_lot.proto
> +  bool vk = 2;
кажется плохо так, когда будем добавлять другие соц сети

2023-01-14 23:47 UTC, Schuyweiz commented on lot/src/proto/model_lot.proto
> +  bool vk = 2;
думаю нужно здесь скорее указывать соц сеть как доступ

2023-01-14 23:47 UTC, Schuyweiz commented on lot/src/proto/waterfall/waterfall.proto
> +  oneof sort {
ох чую тут такая пизда настанет апигв с динамичным роутингом

2023-01-15 10:20 UTC, v1as commented on lot/src/proto/card/card_lot.proto
> +  string price = 8;
В таких случаях обычно добавляют суффикс Str

2023-01-15 10:22 UTC, v1as commented on lot/src/proto/card/card_lot.proto
> +  bool is_favorite = 9;
Согласен с комментарием, в любом случае как минимум стоит убрать префикс is_, вместо него уже есть тип bool.

2023-01-15 10:23 UTC, v1as commented on lot/src/proto/card/card_lot.proto
> +  WaysOfCommunicating ways_of_communicating = 1;
Докину в качестве предложения `ChannelType`

2023-01-15 10:28 UTC, v1as commented on lot/src/proto/model_lot.proto
> +  string date_of_publication = 4;
У такого формата есть недостаток - сложнее дебажить и анализировать, когда будешь смотреть запрос глазами. Обычно такие штуки передают в [ISO_8601](https://en.wikipedia.org/wiki/ISO_8601) (таймзона всегда UTC) а на клиенте уже форматируют как надо.

2023-01-16 21:29 UTC, WolfAlm commented on lot/src/proto/card/card_lot.proto
> +message CardLotRequest {
пока это оставлю под вопросом, будет видно, нужны ли методы или нет и в соответствии с ними и уже решим

2023-01-16 21:29 UTC, WolfAlm commented on lot/src/proto/card/card_lot.proto
> +  string price = 8;
Не, это ответ от нашего бэка, то есть, мобильщики просто делают запросик с id объявления, а я в ответ полноценное превью. 

то есть, это поле -- просто форматинг на стороне бэка

2023-01-16 21:29 UTC, WolfAlm commented on lot/src/proto/card/card_lot.proto
> +  bool is_favorite = 9;
но енам требует какое-то конкретное состояние, а тут может быть 8 различных комбинаций

2023-01-16 21:29 UTC, WolfAlm commented on lot/src/proto/card/card_lot.proto
> +  Photo photo = 6;
не очень поняла про что ты, я тут прикладываю айдишник фотографии, а потом мобильщики будут делать запрос на получение фотографии по айдишникам, а фотографии сами хранятся в БД в виде байтов

Наверное, в идеале вообще переделать на ссылки, и хранить фотки на облаке каком-нить, но это все "потом", я пишу по логике прошлогодной

2023-01-16 21:29 UTC, WolfAlm commented on lot/src/proto/model_lot.proto
> +  string date_of_publication = 4;
это ответ от бэка, а не от мобильщиков, от мобильщиков я не жду даты никогда, потому что я возьму текущее время в момент создания/в момент редактирования

2023-01-16 21:29 UTC, WolfAlm commented on lot/src/proto/model_lot.proto
> +  bool vk = 2;
если добавим, то добавим еще одно поле по идее. Просто типа перечисление(енам) не подходит, тк способов связи может быть выбрано либо 1, либо 2 -- валидация на стороне бэка

2023-01-21 14:20 UTC, Schuyweiz commented on lot/src/proto/model_lot.proto
> +  bool vk = 2;
не понял в чем проблема. Пользователь имеет 3 вида связи, предаем список енамов VK FB GOOGLE
или это то что я слово список забыл смутило?

2023-01-22 22:13 UTC, WolfAlm commented on lot/src/proto/model_lot.proto
> +  bool vk = 2;
> или это то что я слово список забыл смутило?
да, это) в теории можно, спасибо

2023-01-28 11:44 UTC, Schuyweiz approved these changes

2023-01-28 11:45 UTC, merged