[ZV-292] Добавлен метод, который позволяет получать всю семью для Category Service
ZveronHSE/contract pull request #7
Opened 2023-01-14 21:08 UTC by WolfAlm

2023-01-14 23:13 UTC, Schuyweiz requested changes

2023-01-14 23:13 UTC, Schuyweiz commented on parameter/src/proto/category/category.proto
> +  rpc getFamily(CategoryRequest) returns (CategoryResponse);
может лучше `getCategoryTree` все же тут скорее дерево, чем семья 
```suggestion
  rpc getCategoryTree(CategoryRequest) returns (CategoryResponse);
```

2023-01-17 18:25 UTC, dakochik approved these changes

2023-01-17 21:24 UTC, Schuyweiz approved these changes

2023-01-19 19:34 UTC, merged